#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if systemctl is-active --quiet vhs-digitizer.service; then
            systemctl stop vhs-digitizer.service
        fi
        if systemctl is-enabled --quiet vhs-digitizer.service 2>/dev/null; then
            systemctl disable vhs-digitizer.service
        fi
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
